### ISSUE TITLE
Invalid build.fan

### ISSUE THREAD

**Issue by SlimerDude** [xored/f4#113]
Defining the index as `[,]` and not `[:]` gives an F4 build error that prevents the project from ever being built:
```
sys::CastErr: java.lang.ClassCastException: fan.sys.List cannot be cast to fan.sys.Map
	at fan.sys.Err.make(Err.java:37)
	at fan.sys.Method.invoke(Method.java:584)
	at fan.sys.Method$MethodFunc.callOn(Method.java:244)
	at fan.sys.Method.callOn(Method.java:139)
	at fan.f4core.FantomProjectManager.receive(FantomProjectManager.fan:39)
	at fan.concurrent.Actor._dispatch(Actor.java:234)
	at fan.concurrent.Actor._work(Actor.java:204)
	at fan.concurrent.ThreadPool$Worker.run(ThreadPool.java:262)
```

**Comment by SlimerDude** [comment]
Err... I'm not sure what my problem was. The error looks quite clear to me now:
![image](https://user-images.githubusercontent.com/3326741/124909276-2c135700-dfe2-11eb-8374-c53a61d20ab6.png)
