### ISSUE TITLE
Cannot perform Java compilation

### ISSUE THREAD

**Issue by SlimerDude** [xored/f4#133]
If a project with Java Peer code has dependencies on external / non-core pods, then F4 reports the following error during compilation:

```
sys::UnknownPodErr: afxDom
	at fan.sys.UnknownPodErr.make(UnknownPodErr.java:25)
	at fan.sys.Pod.doFind(Pod.java:104)
	at fan.sys.Pod.find(Pod.java:46)
	at fanx.util.TypeParser.find(TypeParser.java:87)
	at fanx.util.TypeParser.loadBasic(TypeParser.java:245)
	at fanx.util.TypeParser.load(TypeParser.java:146)
	at fanx.util.TypeParser.loadFunc(TypeParser.java:196)
	at fanx.util.TypeParser.load(TypeParser.java:124)
	at fanx.util.TypeParser.loadTop(TypeParser.java:113)
	at fanx.util.TypeParser.load(TypeParser.java:73)
	at fan.sys.Type.find(Type.java:45)
	at fanx.emit.FClassEmit.base(FClassEmit.java:44)
	at fanx.emit.FTypeEmit.emit(FTypeEmit.java:73)
	at fanx.emit.FTypeEmit.emit(FTypeEmit.java:47)
	at fan.sys.ClassType.emitToClassFiles(ClassType.java:673)
	at com.xored.fanide.core.JStubGenerator.generateStubs(JStubGenerator.java:63)
	at fan.f4builder.InternalBuilder.compileJava(InternalBuilder.fan:166)
	at fan.f4builder.InternalBuilder.buildPod(InternalBuilder.fan:88)
	at fan.f4builder.Builder.build(Builder.fan:27)
	at fan.f4builder.CompileFan.buildPod(CompileFan.fan:90)
	at fan.f4builder.CompileFan.build(CompileFan.fan:57)
	at org.eclipse.dltk.internal.core.builder.ScriptBuilder.incrementalBuild(ScriptBuilder.java:551)
	at org.eclipse.dltk.internal.core.builder.ScriptBuilder.build(ScriptBuilder.java:175)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:798)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:219)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:262)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:315)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:318)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:370)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:391)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:145)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by SlimerDude** [comment]
This may be related to the forum post [Importing other pods in Java FFI](https://fantom.org/forum/topic/2886)
