### ISSUE TITLE
F4 doesn't compile .java files

### ISSUE THREAD

**Issue by SlimerDude** [xored/f4#77]
A Fantom project with .java files doesn't compile the .java files into the target pod.

Here's a screenshot of a sample project showing the pod contents.

![nojava](https://cloud.githubusercontent.com/assets/3326741/11818844/85ace9a0-a354-11e5-8e61-8fdea0171306.png)

I also see the following in the Fantom Build console:

```
java.io.IOException: Error in writing existing jar file
	at sun.tools.jar.Main.run(Main.java:286)
	at sun.tools.jar.Main.main(Main.java:1288)
```

**Comment by SlimerDude** [comment]
The `.class` files are compiled okay, the problem is when the existing `.jar` file is updated - see [sun.tools.jar.Main.run()](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/sun/tools/jar/Main.java?av=f#284)

Looks like it could be an OS (win) file-system issue - I think perhaps the `.pod` file is locked by another process, but I'm not sure what by.

**Comment by SlimerDude** [comment]
It seems this locking issue is still around - how do I [re-open this issue](https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github#21333938)?
